[package]
name = "vhost"
version = "0.1.0"
authors = ["Liu Jiang <gerry@linux.alibaba.com>"]
repository = "https://github.com/rust-vmm/vhost"
license = "Apache-2.0 or BSD-3-Clause"

[features]
default = []
vhost-vsock = []
vhost-kern = ["vm-memory"]
vhost-user-master = []
vhost-user-slave = []
vhost-net = ["vhost-kern"]

[dependencies]
bitflags = ">=1.0.1"
libc = ">=0.2.39"

vmm-sys-util = ">=0.3.1"
vm-memory = { version = "0.2.0", optional = true }
